### ISSUE TITLE
get_time_info close ncdf?

### ISSUE THREAD

**Issue by hdugan** [USGS-R/glmtools#174]
Referencing: `nc_helpers.R`, `get_time_info` function

Not sure about this, but I think the if statement on Line 61-63, 
    
    if (missing(glm_nc)) {
	 close_glm_nc(glm_nc)
    }

doesn't work, since the code creates a glm_nc object. Should the if statement be deleted? Keep just the close call? 
`close_glm_nc(glm_nc)`

**Comment by lawinslow** [comment]
You mean like this? 
https://github.com/USGS-R/glmtools/pull/173/files

**Comment by lawinslow** [comment]
Also, we still want to selectively close because sometimes that call is part of a larger set of function calls referring to the NC file. We leave the connection open throughout them all. Granted, it isn't clear how much overhead there is if we were to just open/close in each function, but that's not how its done right now.

**Comment by lawinslow** [comment]
@hdugan just noticed that we haven't pushed that update I referenced to GRAN, so you wouldn't have gotten the update. That was an oversight. I'm pushing now.

**Comment by lawinslow** [comment]
@hdugan update is up now. If you update to 0.9.8 this issue is fixed.
